//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class Book
    {
        public int BookID { get; set; }
        [Required(ErrorMessage = "Xin vui lòng nh?p sách"), MaxLength(100, ErrorMessage = "Tên sách không dài h?n 100 ký t?"), DisplayName("Tên sách")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Xin vui lòng ch?n tác gi?"), DisplayName("Tác gi?")]
        public int AuthorID { get; set; }
        [DisplayName("??n giá")]
        public Nullable<decimal> Price { get; set; }
        [DisplayName("Hình ?nh")]
        public string Images { get; set; }
        [Required(ErrorMessage = "Xin vui lòng ch?n ch? ?? sách"), DisplayName("Ch? ?? sách")]
        public int CategoryID { get; set; }
        [DisplayName("Mô t?")]
        public string Description { get; set; }
        [DisplayName("Ngày xu?t b?n"), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Published { get; set; }
        [DisplayName("S? l?n xem")]
        public Nullable<int> ViewCount { get; set; }

        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
    }
}
